#!/bin/sh

### BEGIN INIT INFO
# Provides: gmediarender
# Required-Start: $remote_fs $syslog $all 
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start GMediaRender at boot time
# Description: Start GMediaRender at boot time.
### END INIT INFO

# User and group the daemon will be running as. On the Raspberry Pi, let's use
# the default user.
DAEMON_USER="pi:audio"

# Device name as it will be advertised to and shown in the UPnP controller UI.
# Some string that helps you recognize the player, e.g. "Livingroom Player"
UPNP_DEVICE_NAME=`hostname`

# Initial volume in decibel. 0.0 is 'full volume', -10 correspondents to '75' on
# the exported volume scale (Note, this does not change the ALSA volume, only
# internal to gmrender. So make sure to leave the ALSA volume always to 100%).
INITIAL_VOLUME_DB=-10

# If you explicitly choose a specific ALSA device here (find them with 'aplay -L'), then
# gmediarenderer will use that ALSA device to play audio.
# Otherwise, whatever default is configured for gstreamer for the '$DAEMON_USER' is
# used.
#ALSA_DEVICE="iec958"
RET=`dpkg -l pulseaudio`
if [ $? -eq 0 ] ; then
	PULSEAUDIO_DEVICE=`aplay -l|awk '/^card 0/ {print $3}'`
else
	ALSA_DEVICE="sysdefault"
fi

# Path to the gmediarender binary.
BINARY_PATH=/usr/local/bin/gmediarender

LOG_PATH='/var/log/gmediarender.log'
[ ! -f "$LOG_PATH" ] && touch /var/log/gmediarender.log && chown pi $LOG_PATH

if [ -n "$PULSEAUDIO_DEVICE" ] ; then
	GS_SINK_PARAM="--gstout-audiosink=autoaudiosink"
	GS_DEVICE_PARAM="--gstout-audiodevice=$PULSEAUDIO_DEVICE"
elif [ -n "$ALSA_DEVICE" ] ; then
	GS_SINK_PARAM="--gstout-audiosink=alsasink"
	GS_DEVICE_PARAM="--gstout-audiodevice=$ALSA_DEVICE"
fi

# A simple stable UUID, based on this systems' first ethernet devices MAC address,
# only using tools readily available to generate.
UPNP_UUID=`ip link show | awk '/ether/ {print "salt:)-" $2}' | head -1 | md5sum | awk '{print $1}'`
LOG="--logfile=$LOG_PATH"

USER=root
HOME=/root
export USER HOME
case "$1" in
	start)
		echo "Starting GMediaRender"
		start-stop-daemon -x $BINARY_PATH -c "$DAEMON_USER" -S -- -f "$UPNP_DEVICE_NAME" -d -u "$UPNP_UUID" $GS_SINK_PARAM $GS_DEVICE_PARAM --gstout-initial-volume-db=$INITIAL_VOLUME_DB $LOG
		;;

	stop)
		echo "Stopping GMediaRender"
		start-stop-daemon -x $BINARY_PATH -K
		;;

	*)
		echo "Usage: /etc/init.d/gmediarender {start|stop}"
		exit 1
		;;
esac

exit 0
